//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mockup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchiveReturnedSale
    {
        public int ArchiveId { get; set; }
        public Nullable<System.DateTime> DeletedTime { get; set; }
        public Nullable<int> SaleId { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
    }
}
