//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mockup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchiveEnterHistory
    {
        public int ArchiveId { get; set; }
        public Nullable<System.DateTime> DeletedTime { get; set; }
        public Nullable<int> EntryId { get; set; }
        public Nullable<int> WorkerId { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public Nullable<bool> IsSuccessful { get; set; }
    }
}
