//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mockup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchiveWorker
    {
        public int ArchiveId { get; set; }
        public Nullable<System.DateTime> DeletedTime { get; set; }
        public Nullable<int> WorkerId { get; set; }
        public Nullable<int> SurnameId { get; set; }
        public Nullable<int> FirstnameId { get; set; }
        public Nullable<int> DepartmentCode { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public Nullable<int> ImgId { get; set; }
    }
}
