//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mockup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListProductsOfDepartment
    {
        public string ProductId { get; set; }
        public string ProductName { get; set; }
        public int DepartmentCode { get; set; }
        public Nullable<decimal> SUM_Quantity { get; set; }
        public string N1 { get; set; }
        public decimal Price { get; set; }
    }
}
