//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mockup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListSale
    {
        public int SaleId { get; set; }
        public System.DateTime Datetime { get; set; }
        public string Worker { get; set; }
        public string ProductName { get; set; }
        public string Sold { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public string DepartmentName { get; set; }
        public int DepartmentCode { get; set; }
        public int WorkerId { get; set; }
        public string ProductArticle { get; set; }
        public decimal SoldQuantity { get; set; }
    }
}
