//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mockup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListShopment
    {
        public int EntryId { get; set; }
        public System.DateTime Datetime { get; set; }
        public string Worker { get; set; }
        public string ProductName { get; set; }
        public string Shipped { get; set; }
        public string DepartmentName { get; set; }
        public int DepartmentCode { get; set; }
        public string ProductArticleNumber { get; set; }
    }
}
