//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mockup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListProduct
    {
        public string ProductArticleNumber { get; set; }
        public string ShortName { get; set; }
        public string ProductName { get; set; }
        public decimal Price { get; set; }
    }
}
