//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mockup.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UP_02_01_DBEntities : DbContext
    {
        public UP_02_01_DBEntities()
            : base("name=UP_02_01_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ArchiveDepartment> ArchiveDepartments { get; set; }
        public virtual DbSet<ArchiveEnterHistory> ArchiveEnterHistories { get; set; }
        public virtual DbSet<ArchiveFirstname> ArchiveFirstnames { get; set; }
        public virtual DbSet<ArchiveImage> ArchiveImages { get; set; }
        public virtual DbSet<ArchiveMeasurementUnit> ArchiveMeasurementUnits { get; set; }
        public virtual DbSet<ArchiveProduct> ArchiveProducts { get; set; }
        public virtual DbSet<ArchiveReturnedSale> ArchiveReturnedSales { get; set; }
        public virtual DbSet<ArchiveRole> ArchiveRoles { get; set; }
        public virtual DbSet<ArchiveSale> ArchiveSales { get; set; }
        public virtual DbSet<ArchiveShipmentsToAndWriteOffsFromWarehous> ArchiveShipmentsToAndWriteOffsFromWarehouses { get; set; }
        public virtual DbSet<ArchiveSurname> ArchiveSurnames { get; set; }
        public virtual DbSet<ArchiveTypesOfStorageMovement> ArchiveTypesOfStorageMovements { get; set; }
        public virtual DbSet<ArchiveWorker> ArchiveWorkers { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<EnterHistory> EnterHistories { get; set; }
        public virtual DbSet<Firstname> Firstnames { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<MeasurementUnit> MeasurementUnits { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<ShipmentsToAndWriteOffsFromWarehous> ShipmentsToAndWriteOffsFromWarehouses { get; set; }
        public virtual DbSet<Surname> Surnames { get; set; }
        public virtual DbSet<TypesOfStorageMovement> TypesOfStorageMovements { get; set; }
        public virtual DbSet<Worker> Workers { get; set; }
        public virtual DbSet<ListHistory> ListHistories { get; set; }
        public virtual DbSet<ListSale> ListSales { get; set; }
        public virtual DbSet<ListShopment> ListShopments { get; set; }
        public virtual DbSet<ListProductsOfDepartment> ListProductsOfDepartments { get; set; }
        public virtual DbSet<ListProduct> ListProducts { get; set; }
        public virtual DbSet<ListWorker> ListWorkers { get; set; }
        public virtual DbSet<ReturnedSale> ReturnedSales { get; set; }
    }
}
