//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mockup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Sales = new HashSet<Sale>();
            this.ShipmentsToAndWriteOffsFromWarehouses = new HashSet<ShipmentsToAndWriteOffsFromWarehous>();
        }
    
        public string ProductArticleNumber { get; set; }
        public int MeasurementUnitId { get; set; }
        public string ProductName { get; set; }
        public decimal Price { get; set; }
    
        public virtual MeasurementUnit MeasurementUnit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShipmentsToAndWriteOffsFromWarehous> ShipmentsToAndWriteOffsFromWarehouses { get; set; }
    }
}
