//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mockup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnedSale
    {
        public int SaleId { get; set; }
        public string Reason { get; set; }
        public System.DateTime Datetime { get; set; }
    
        public virtual Sale Sale { get; set; }
    }
}
