//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mockup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int SaleId { get; set; }
        public int DepartmentCode { get; set; }
        public string ProductArticle { get; set; }
        public int WorkerId { get; set; }
        public System.DateTime Datetime { get; set; }
        public decimal SoldQuantity { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Product Product { get; set; }
        public virtual Worker Worker { get; set; }
        public virtual ReturnedSale ReturnedSale { get; set; }
    }
}
