//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mockup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipmentsToAndWriteOffsFromWarehous
    {
        public int EntryId { get; set; }
        public int DepartmentCode { get; set; }
        public string ProductId { get; set; }
        public int StorageWorkerId { get; set; }
        public int TypeId { get; set; }
        public System.DateTime Datetime { get; set; }
        public decimal Quantity { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Product Product { get; set; }
        public virtual Worker Worker { get; set; }
        public virtual TypesOfStorageMovement TypesOfStorageMovement { get; set; }
    }
}
