//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mockup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Worker()
        {
            this.EnterHistories = new HashSet<EnterHistory>();
            this.Sales = new HashSet<Sale>();
            this.ShipmentsToAndWriteOffsFromWarehouses = new HashSet<ShipmentsToAndWriteOffsFromWarehous>();
        }
    
        public int WorkerId { get; set; }
        public int SurnameId { get; set; }
        public int FirstnameId { get; set; }
        public Nullable<int> DepartmentCode { get; set; }
        public int RoleId { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public Nullable<int> ImgId { get; set; }
    
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnterHistory> EnterHistories { get; set; }
        public virtual Firstname Firstname { get; set; }
        public virtual Image Image { get; set; }
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShipmentsToAndWriteOffsFromWarehous> ShipmentsToAndWriteOffsFromWarehouses { get; set; }
        public virtual Surname Surname { get; set; }
    }
}
