--dependency level 1
IF OBJECT_ID (N'dbo.GuestsInRooms', N'U') IS NOT NULL
	DROP TABLE dbo.GuestsInRooms
GO
--dependency level 0
IF OBJECT_ID (N'dbo.Guests', N'U') IS NOT NULL
	DROP TABLE dbo.Guests
GO

IF OBJECT_ID (N'dbo.Rooms', N'U') IS NOT NULL
	DROP TABLE dbo.Rooms
GO
--dependency level 0
CREATE TABLE Guests
(
	GUEST_ID INT IDENTITY(1,1)
,	GUEST_NAME NVARCHAR(200) NOT NULL
,	CONSTRAINT PK_Guests_GUEST_ID PRIMARY KEY (GUEST_ID)
)
GO

CREATE TABLE Rooms
(
	ROOM_ID INT IDENTITY(1,1)
--,	BEDS_COUNT INT NOT NULL
,	ROOM_NAME NVARCHAR(20) NOT NULL
,	CONSTRAINT PK_Rooms_ROOM_ID PRIMARY KEY (ROOM_ID)
,	CONSTRAINT UQ_Rooms_ROOM_NAME UNIQUE (ROOM_NAME)
)
GO
--dependency level 1
CREATE TABLE GuestsInRooms
(
	ROOM_ID INT NOT NULL
,	GUEST_ID INT NOT NULL
,	CONSTRAINT FK_GuestsInRooms_to_Rooms FOREIGN KEY (ROOM_ID) REFERENCES Rooms(ROOM_ID)  
,	CONSTRAINT FK_GuestsInRooms_to_Guests FOREIGN KEY (GUEST_ID) REFERENCES Guests(GUEST_ID)  
,	CONSTRAINT PK_GuestsInRooms PRIMARY KEY (ROOM_ID, GUEST_ID)
)
GO