IF OBJECT_ID('DBO.STRINGS', N'U') is not NULL
    DROP TABLE STRINGS;
GO
IF OBJECT_ID('DBO.USERS', N'U') is not NULL
    DROP TABLE USERS;
GO

CREATE TABLE Users (
    ID       INT PRIMARY KEY IDENTITY (1, 1),
    Login    NVARCHAR (50)  unique not NULL,
    Password NVARCHAR (100) not NULL
)
GO

CREATE TABLE STRINGS (
    ID INT PRIMARY KEY IDENTITY(1,1),
    UserId INT FOREIGN KEY REFERENCES USERS(ID) NOT NULL,
    STRING NVARCHAR(MAX)
)
GO