//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using Lab2DbFirst;
using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class MDK_02_02_GRUZDEVEntities : DbContext
{
    public MDK_02_02_GRUZDEVEntities()
        : base("name=MDK_02_02_GRUZDEVEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Cours> Courses { get; set; }
    public virtual DbSet<Firstname> Firstnames { get; set; }
    public virtual DbSet<StudentCours> StudentCourses { get; set; }
    public virtual DbSet<Student> Students { get; set; }
    public virtual DbSet<Surname> Surnames { get; set; }
    public virtual DbSet<Teacher> Teachers { get; set; }
}
